devtools::document()
devtools::build_vignettes()
devtools::build()
devtools::install(build_vignettes = TRUE)
#install.packages("/media/PhD/GitHub/essexBigdata_0.1.0.tar.gz", repos = NULL, type = "source")
library(BristolVis)

data("med")
head(med)
data(birthweight, package="BristolVis")
head(birthweight)
data(bmi)
head(bmi)
data(bmov)
head(bmov)
range(med$time)
?med
vignette("practical6", package = "BristolVis")
vignette("answers6", package = "BristolVis")
