devtools::document()
devtools::build_vignettes()
devtools::build()
devtools::install(build_vignettes = TRUE)
library(BristolVis)

data("med")
head(med)
?med
data(birthweight, package="BristolVis")
head(birthweight)
data(bmi)
head(bmi)
data(bmov)
head(bmov)

vignette("prac_base", package = "BristolVis")
vignette("ans_base", package = "BristolVis")
vignette("prac_advanced", package = "BristolVis")
vignette("ans_advanced", package = "BristolVis")
vignette("prac_AdvMore", package = "BristolVis")
vignette("ans_AdvMore", package = "BristolVis")
vignette("prac_interactive", package = "BristolVis")
vignette("ans_interactive", package = "BristolVis")

vignette("practical7", package = "BristolVis")
vignette("answers7", package = "BristolVis")

install.packages("drat")
drat::addRepo("statcourses")
install.packages("BristolVis")
